---
deployment:
  tasks:
    - export DEPLOYPATH=/home/westernhan/public_html/
    - /bin/cp *.* $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH